version: "3"

services:

  db:
      image: postgres:14-alpine
      ports:
          - "5433:5432"
      env_file:
           - .env
  app:
    build: .
    command:
      sh -c "python3 manage.py wait_for_db &&
            python3 manage.py migrate &&
            python3 manage.py loaddata fixture_file.json &&
            python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
