# Generated by Django 4.2.6 on 2023-10-20 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["name"]},
        ),
    ]
